services:
  backend:
    build:
      context: .
      dockerfile: LearnTogether/LearnTogether.API/Dockerfile
    ports:
      - "5000:8080"  
    environment:
      ConnectionStrings__Default: "Host=postgres;Database=LearnTogetherDb;Username=postgres;Password=LearnTogetherPassword"
    depends_on:
      - postgres
  postgres:
    image: postgres:15  
    environment:        
      POSTGRES_USER: postgres     
      POSTGRES_PASSWORD: geocodeFT 
      POSTGRES_DB: LearnTogetherDb    
    ports:
      - "5432:5432" 
    volumes:
      - db_data:/var/lib/postgresql/data
  frontend:
    build:
      context: ./Frontend
      dockerfile: Dockerfile
    ports:
      - "3000:80"
    depends_on:
      - backend
volumes:
  db_data:  
